Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.10.100"
  
  # Sync app folder
  config.vm.synced_folder ".", "/home/vagrant/app"
  # upload and execute a script within the guest machine
  config.vm.provision "shell", path: "provision.sh"     
  
end
